spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: OIPASecurityTool
  datasource:
    secondary-dev:
      jdbc-url: jdbc:oracle:thin:@//10.10.3.246:1521/OIPADEVDB
      username: OIPA_PAS
      password: OIPA_PAS
      driver-class-name: oracle.jdbc.OracleDriver
      hikari:
        maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
    show-sql: true

server:
  port: 8015
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: tomcat

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      orm:
        jdbc:
          bind: TRACE